#!/bin/python3
import getpass
import requests
import sys
import os

def get_web_string(url):
    response = requests.get(url)
    
    if response.status_code == 200:
        return response.text
    else:
        print(f"REQUEST ERR - {response.status_code}")
        sys.exit()

if __name__ == "__main__":
    if len(sys.argv) <= 1:
        print("PROGRAM ERR - NO ARGUMENTS")
        sys.exit()

    sys.argv[1] = sys.argv[1].lower().strip()

    if sys.argv[1] == "setup":
        os.system("echo 'source ~/.bashrc' > ~/.pkgsetup")
        print("SUCCESSFUL!")
        sys.exit()

    if sys.argv[1] == "reset":
        os.system("rm -rf ~/.pkgsetup ~/.pkgbin")
        print("SUCCESSFUL!")
        sys.exit()

    if sys.argv[1] == "prep":
        os.system("chmod +x ~/.pkgsetup && /bin/bash -c 'source ~/.pkgsetup'")
        print("SUCCESSFUL!")
        sys.exit()

    
    string = get_web_string(f"https://packages.debian.org/trixie/amd64/{sys.argv[1]}/download")

    string_start = string.index("http://ftp.us.debian.org/debian/pool/main/")
    string = string[string_start:]
    string_end = string.index("\"")
    string = string[:string_end]

    try:
        os.system(f"wget -O {sys.argv[1]}.deb {string}")

        if not os.path.exists(f"/home/{getpass.getuser()}/.pkgbin"):
            os.system("mkdir ~/.pkgbin")

        if not os.path.exists(f"/home/{getpass.getuser()}/.pkgbin/{sys.argv[1]}"):
            os.system(f"dpkg -x {sys.argv[1]}.deb ~/.pkgbin/{sys.argv[1]}")

        else:
            print(f"PROGRAM ERR - PATH .pkgbin/{sys.argv[1]} EXISTS")
            os.remove(f"{sys.argv[1]}.deb")
            sys.exit()
        
        add_path_string = f"echo PATH=\"~/.pkgbin/{sys.argv[1]}/usr/bin/:$PATH\""

        with open(f"/home/{getpass.getuser()}/.pkgsetup", "r") as f:
            data = f.read()

        with open(f"/home/{getpass.getuser()}/.pkgsetup", "w") as f:
            f.write(f"{data}\n{add_path_string}")
            print(f"{data}\n{add_path_string[5:]}")


        os.system("chmod +x ~/.pkgsetup && /bin/bash -c 'source ~/.pkgsetup'")

        os.remove(f"{sys.argv[1]}.deb")

        print("INSTALL SUCCESSFUL probably idk")

    except Exception as e:
        os.remove(f"{sys.argv[1]}.deb")
        os.system(f"rm -rf ~/.pkgbin/{sys.argv[1]}")

        print(f"UNHANDLED ERR - {e}")
